[build]
    publish = "frontend/dist"
[[redirects]]
  from = "/api/*"
  to = "https://avtechfin-za2p.onrender.com/api/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200